import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import { CLI_VERSION } from "./features/cli-version";

const rawArgs = hideBin(process.argv);

if (rawArgs.length === 1 && (rawArgs[0] === "--version" || rawArgs[0] === "-v")) {
  process.stdout.write(`${CLI_VERSION}\n`);
  process.exit(0);
}

const [
  { topLevelCommandModules, topLevelCommandNames },
  dashboardCommand,
  { shouldEnsureApiForCommand },
  { findGitRoot, readConfig },
  { ensureApi },
  { dispatchExtensionCliCommand },
  { firstCommandToken, rawValueFor, shouldDispatchExtensionCommand },
  { loadExtensionNamespaces },
  { resolveRootHelpRuntime },
  { createCliCommandTracker },
  { resolveCliSessionId },
  { shouldLoadEmbedManifest },
] = await Promise.all([
  import("./adapters/cli/commands"),
  import("./adapters/cli/commands/dashboard"),
  import("./features/cli-api-startup"),
  import("./features/config/config"),
  import("./features/ensure-api"),
  import("./features/extensions/extension-cli-router"),
  import("./features/extensions/extension-command-routing"),
  import("./features/extensions/root-help-namespaces"),
  import("./features/extensions/root-help-runtime"),
  import("./features/logging/cli-command-log"),
  import("./features/sessions/resolve-cli-session-id"),
  import("./features/should-load-embed-manifest"),
]);

if (shouldLoadEmbedManifest()) {
  // Side-effect import: registers files for Bun.embeddedFiles in compiled binaries.
  // Generated by build scripts.
  await import("./_embed-manifest.generated");
}

// True-core commands only. Domain namespaces (the ticket board's
// tickets/statuses/tags) are not listed here — they resolve entirely through
// extension-contributed commands.
const staticTopLevelCommands = new Set(["dashboard", ...topLevelCommandNames]);

const hasProjectConfig = () => {
  const root = findGitRoot(process.cwd());
  return Boolean(root && readConfig(root));
};

const resolveRequestedApiUrl = () => {
  if (process.env.PSTDIO_API_URL) return process.env.PSTDIO_API_URL;
  const apiPort = rawValueFor(rawArgs, "api-port");
  return apiPort ? `http://127.0.0.1:${apiPort}` : undefined;
};

const applyApiPortFromArgs = () => {
  if (process.env.PSTDIO_API_URL || process.env.PSTDIO_API_PORT) return;
  const apiPort = rawValueFor(rawArgs, "api-port");
  if (apiPort) process.env.PSTDIO_API_PORT = apiPort;
};

const commandTracker = createCliCommandTracker({
  rawArgs,
  sessionId: resolveCliSessionId({ env: process.env }),
});

if (shouldDispatchExtensionCommand({ rawArgs, staticTopLevelCommands, hasProjectConfig })) {
  try {
    applyApiPortFromArgs();
    const requestedApiUrl = resolveRequestedApiUrl();
    await ensureApi(requestedApiUrl);
    commandTracker.captureArgv({ _: rawArgs });
    const exitCode = await dispatchExtensionCliCommand({
      rawArgs,
      onCommandResolved: (command) => {
        commandTracker.setMutating(command.mutating === true);
        commandTracker.logStart();
      },
    });
    if (exitCode === null) {
      // The token was not an extension namespace; fall through to yargs so root help/error formatting stays canonical.
    } else {
      if (exitCode === 0) {
        commandTracker.logSuccess();
      } else {
        commandTracker.logFailure(`Extension command exited with status ${exitCode}`);
      }
      process.exit(exitCode);
    }
  } catch (error) {
    if (error instanceof Error && error.message.startsWith("Could not start the pstdio API.")) {
      // Let yargs keep the normal root help for unknown commands when extension metadata is unavailable.
    } else {
      commandTracker.logFailure(error);
      const message = error instanceof Error ? error.message : String(error);
      process.stderr.write(`Error: ${message}\n`);
      process.exit(1);
    }
  }
}

const cli = yargs(rawArgs)
  .scriptName("pstdio")
  .version(CLI_VERSION)
  .strict()
  .fail((msg, err, yargs) => {
    commandTracker.logFailure(err ?? msg);
    if (err) {
      process.stderr.write(`Error: ${err.message}\n`);
      process.exit(1);
    }
    process.stderr.write(`${msg}\n\n`);
    yargs.showHelp("error");
    process.stderr.write("\n");
    process.exit(1);
  })
  .middleware(async (argv) => {
    commandTracker.captureArgv(argv);
    commandTracker.logStart();

    if (!shouldEnsureApiForCommand(argv)) return;

    applyApiPortFromArgs();
    await ensureApi(resolveRequestedApiUrl());
  })
  .command(dashboardCommand);

for (const mod of topLevelCommandModules) {
  // biome-ignore lint/suspicious/noExplicitAny: yargs CommandModule union requires cast
  cli.command(mod as any);
}

// Surface extension namespaces (e.g. `tickets`) alongside core commands in the
// root help. API-gated and best-effort: when the server is reachable we list the
// installed namespaces, otherwise root help degrades to core commands only.
if (!firstCommandToken(rawArgs) && (rawArgs.includes("--help") || rawArgs.includes("-h"))) {
  const { apiUrl, token } = await resolveRootHelpRuntime(resolveRequestedApiUrl());
  process.env.PSTDIO_API_URL = apiUrl;
  if (token) process.env.PSTDIO_API_TOKEN = token;
  const namespaces = await loadExtensionNamespaces({
    healthUrl: `${apiUrl}/healthz`,
    exclude: staticTopLevelCommands,
  });
  for (const summary of namespaces) {
    cli.command(`${summary.namespace} [command]`, summary.description);
  }
}

cli
  .parseAsync()
  .then(() => {
    commandTracker.logSuccess();
  })
  .catch((error: unknown) => {
    commandTracker.logFailure(error);
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`Error: ${message}\n`);
    process.exit(1);
  });
